// ignore_for_file: constant_identifier_names

import 'package:flutter/material.dart';

class Territories extends StatelessWidget {
  Territories({Key? key}) : super(key: key);

  List<String> countires = <String>[
    'Ingria',
    'Pomorie',
    'Chernozemie',
    'Muscovy',
    'Ural',
    'IdelUral',
    'WestSiberianPlain',
    'Volga',
    'Cossackia',
    'Circassia',
    'Dagestan',
    'EastKazakhstan',
    'WestKazakhstan',
    'Uzbekistan',
    'Turkmenistan',
    'Georgia',
    'Azerbaijan',
    'Armenia',
    'Turkey',
    'Iran',
    'Iraq',
    'Syria',
    'Kuwait',
    'Lebanon',
    'Israel',
    'Jordan',
    'SaudiArabia',
    'Egypt',
    'Libya',
    'Tunisia',
    'Algeria',
    'Morocco',
    'Finland',
    'Sweden',
    'Norway',
    'Iceland',
    'Scotland',
    'England',
    'Ireland',
    'Wales',
    'Portugal',
    'Spain',
    'France',
    'Belgium',
    'Netherlands',
    'Switzerland',
    'Germany',
    'Denmark',
    'Italy',
    'CzechRepublic',
    'Slovakia',
    'Austria',
    'Hungary',
    'Slovenia',
    'Croatia',
    'Estonia',
    'Lativa',
    'Lithuania',
    'Belarus',
    'Ukraine',
    'Poland',
    'Boznia',
    'Serbia',
    'Romania',
    'Moldova',
    'Bulgaria',
    'Macedonia',
    'Albania',
    'Greece',
  ];

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
